---
title: "generate samtools"
author: "Caroline Wheeler"
date: "8/23/2024"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## get sample names
```{r cars}
fastq.dir <- "/fs/ess/PAS1695/projects/bewell/data/fastqs/bowties"

all.files <- list.files(fastq.dir)

snames <- gsub(".sam", "", all.files)
```

qsub -t 0-{x} fastp.pbs
```{r}
fileOut<-file(paste0("/fs/ess/PAS1695/projects/bewell/scripts/pbs/bewell-samtools.pbs"))
 
writeLines(c(paste0("#PBS -N bewell-samtools"),
               "#PBS -l walltime=24:00:00",
               "#PBS -l nodes=1:ppn=28",
               "#PBS -j oe",
               "#PBS -m ae",
               "#PBS -A PAS1695",
               "",
               
               #List sample naames in a way that can be indexed
               paste0("snames=('", paste(snames, collapse = "' '"), "')"),
             
               "",
               "module load samtools",
               "",
          
               "samtools fastq -f 4 /fs/ess/PAS1695/projects/bewell/data/fastqs/bowties/${snames[$PBS_ARRAY_INDEX]}.sam > /fs/ess/PAS1695/projects/bewell/data/fastqs/ultra-filtered/${snames[$PBS_ARRAY_INDEX]}.fastq 2> /fs/ess/PAS1695/projects/bewell/scripts/logs/samtools-sam2fastq-${snames[$PBS_ARRAY_INDEX]}.log"
               
  ),
  
  fileOut
  )
```

