---
title: "bowtie2"
author: "Caroline Wheeler"
date: "8/22/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## get sample names
```{r cars}
fastq.dir <- "/fs/ess/PAS1695/projects/bewell/data/fastqs/sra-scrubbed"

all.files <- list.files(fastq.dir)

snames <- gsub(".fastq", "", all.files)
```

qsub -t 0-{x} fastp.pbs
```{r}

fileOut<-file(paste0("/fs/ess/PAS1695/projects/bewell/scripts/pbs/bewell-bowtie2.pbs"))
  
fastq <- paste0(fastq.dir, "/${snames[$PBS_ARRAY_INDEX]}.fastq")
 
writeLines(c(paste0("#PBS -N bewell-bowtie2"),
               "#PBS -l walltime=10:00:00",
               "#PBS -l nodes=1:ppn=28",
               "#PBS -j oe",
               "#PBS -m ae",
               "#PBS -A PAS1695",
               "",
               
               #List sample naames in a way that can be indexed
               paste0("snames=('", paste(snames, collapse = "' '"), "')"),
               
               "source activate bowtie2",
               "",
          
               "bowtie2 -x /fs/ess/PAS1695/db/bowtie2-ultrafiltering/merged_ref -U /fs/ess/PAS1695/projects/bewell/data/fastqs/sra-scrubbed/${snames[$PBS_ARRAY_INDEX]}.fastq -S /fs/ess/PAS1695/projects/bewell/data/fastqs/bowties/${snames[$PBS_ARRAY_INDEX]}.sam -p 8 2> /fs/ess/PAS1695/projects/bewell/scripts/logs/bowtie2-${snames[$PBS_ARRAY_INDEX]}.log"
               
  ),
  
  fileOut
  )
```