---
title: "make data tables"
author: "Caroline Wheeler"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reshape2)
```

read in metaphlan tables and merge
```{r}
barcodes <- read.csv("/fs/ess/PAS1695/projects/bewell/data/participants/bewell_barcodes.csv")

fq.df <- as.data.frame(list.files("/fs/ess/PAS1695/projects/bewell/data/profiled")) 

fq.df <- fq.df %>%
  mutate(sampnames = substr(fq.df$`list.files("/fs/ess/PAS1695/projects/bewell/data/profiled")`, 10, 19))

mettab.ls <- lapply(fq.df$sampnames, function(x) read.table(paste0("/fs/ess/PAS1695/projects/bewell/data/profiled/profiled_", x, ".txt"),
                                                            header = F, sep = "\t", stringsAsFactors = F))

names(mettab.ls) <- fq.df$sampnames

ID <- fq.df$sampnames

mettab.ls <- mapply(function(x,y) "[<-"(x, "sample", value = y),
               mettab.ls, ID, SIMPLIFY = FALSE)

mettab.ls <- mettab.ls[-63]

metab.df <- bind_rows(lapply(fq.df$sampnames, function(x) mettab.ls[[x]]))

metab.df.form <- metab.df %>%
  dplyr::rename("Taxonomy" = "V1",
         "TaxNum" = "V2",
         "RelAbun" = "V3",
         "Alternative.Tax" = "V4")

df <- merge(barcodes, metab.df.form)
df$id <- as.character(df$id)
```

add timepoint value
```{r}
subs <- read_csv("/fs/ess/PAS1695/projects/bewell/data/participants/bewell_subjects.csv")

keep <- melt(subs, id.vars=1:3) %>%
  dplyr::rename("id" = value)

df <- merge(keep, df)
```

save table
```{r}
write.csv(df,"/fs/ess/PAS1695/projects/bewell/data/bewell_taxonomy_relAbun.csv", row.names = FALSE)
```

## Create long form tables for each taxonomic level

Seperate taxonomic levels
```{r}
df <- df %>%
  mutate(sampleID = paste0(Subject.Number, "-", variable)) %>%
  select(sampleID, Taxonomy, RelAbun)

taxa <- df %>% 
  separate(Taxonomy, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"), "\\|")

get_level <- function(lev, next_lev){
  temp <- taxa %>%
    filter(is.na(taxa[,next_lev])) %>%
    select(sampleID, lev, RelAbun)

  return(temp)
}

taxa_king <- get_level("Kingdom", "Phylum")
taxa_phyl <- get_level("Phylum", "Class") %>% filter(!(is.na(Phylum)))
taxa_class <- get_level("Class", "Order") %>% filter(!(is.na(Class)))
taxa_ord <- get_level("Order", "Family") %>% filter(!(is.na(Order)))
taxa_fam <- get_level("Family", "Genus") %>% filter(!(is.na(Family)))
taxa_gen <- get_level("Genus", "Species") %>% filter(!(is.na(Genus)))
  
taxa_spec <- taxa %>%
  select(sampleID, Species, RelAbun) %>%
  filter(!(is.na(Species)))
```


change to wide form
```{r}
go_wide <- function(df, level){
  d <- spread(df, key = level, value = RelAbun) 
  d[is.na(d)] <- 0
  d2 <- d[,-1]
  rownames(d2) <- d[,1]
  return(d2)
}

df_king <- go_wide(taxa_king, "Kingdom")
df_phyl <- go_wide(taxa_phyl, "Phylum")
df_class <- go_wide(taxa_class, "Class")
df_ord <- go_wide(taxa_ord, "Order")
df_fam <- go_wide(taxa_fam, "Family")
df_gen <- go_wide(taxa_gen, "Genus")
df_spec <- go_wide(taxa_spec, "Species")
```

Save data tables
```{r}
write.csv(df_king,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_king.csv")
write.csv(df_phyl,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_phyl.csv")
write.csv(df_class,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_class.csv")
write.csv(df_ord,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_ord.csv")
write.csv(df_fam,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_fam.csv")
write.csv(df_gen,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_gen.csv")
write.csv(df_spec,"/fs/ess/PAS1695/projects/bewell/data/RelAbun/RelAbun_spec.csv")
```



