---
title: "participant-demographics"
author: "Dan Spakowicz"
date: "1/7/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(tableone)
library(flextable)

source("00-paths.R")
```

```{r}
y <- readxl::read_xlsx(file.path(paths$box, 
                                 "participants", 
                                 "Be Well Study Schedule.xlsx"),
                       trim_ws = TRUE,
                       sheet = 2)

head(y)
```

Get the first sheet to retrieve the dropout date

```{r}
x <- readxl::read_xlsx(file.path(paths$box, 
                                 "participants", 
                                 "Be Well Study Schedule.xlsx"),
                       trim_ws = TRUE,
                       skip = 1,
                       sheet = 1) %>%
  select(`Subject ID`, `Drop Out`)

head(x)
```

Process dropout to a logical

```{r}
do <- 
  x %>%
  mutate(dropout = if_else(is.na(`Drop Out`),
                           true = FALSE,
                           false = TRUE)) %>%
  select(-`Drop Out`)
```



```{r}
df <- 
  y %>%
  mutate(recruitment.style = if_else(`how did you hear about us?` == "LCSC",
                                     true = "in person",
                                     false = "social media",
                                     missing = "unknown"),
         across(c("Gender", "Smoking status", "Race/ethnicity"), tolower),
         `Race/ethnicity` = if_else(`Race/ethnicity` == "white",
                                    true = "caucasian",
                                    false = `Race/ethnicity`),
         `Race/ethnicity` = if_else(`Race/ethnicity` == "white caucasian",
                                    true = "caucasian",
                                    false = `Race/ethnicity`),
         `Race/ethnicity` = if_else(`Race/ethnicity` == "black",
                                    true = "african american",
                                    false = `Race/ethnicity`),
         `Race/ethnicity` = if_else(`Race/ethnicity` == "african",
                                    true = "african american",
                                    false = `Race/ethnicity`),
         across(c("Gender", "Smoking status", "Race/ethnicity"),
                as.factor)
         ) %>%
  left_join(do)
  

head(df)
```

```{r}
table(df$`how did you hear about us?`)
```

```{r}
table(df$recruitment.style)
```

```{r}
table(df$recruitment.style, df$dropout)
```

```{r}
fisher.test(df$recruitment.style, df$dropout)
```


Create a table of the results stratified by `recruitment.style`.

```{r}
str(df$Gender)

listVars <- c("Age", "Gender", "Smoking status", "Race/ethnicity", "dropout")
catVars <- c("Gender", "Smoking status", "Race/ethnicity", "dropout")
```

```{r table 1}
table1 <- CreateTableOne(vars = listVars,
                         data = df,
                         factorVars = catVars,
                         strata = "recruitment.style")
table1
```

```{r}
table1p <- print(table1, printToggle = FALSE)

# flextable 

table2 <- table1p %>%

  as.data.frame() %>%
  
  rownames_to_column("Variables")%>%
  
  flextable() %>%
  
  autofit(add_w = 0.2) %>%
  
  align(align = "left") %>%
  
  align(align = "left", part = "header") %>%
  
  add_header_lines("Table 1: Demographics stratified by recruitment style.")

kableone(table1)
print(table2)
```

```{r}

tab3Mat <- print(table1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)

## Save to a CSV file
write.csv(tab3Mat, file = "../data/derived/demographics-table.csv")
```

```{r}
table(df$`Smoking status`, df$Gender)
```

```{r}
on.study <- 
  df %>%
  filter(!dropout)

table(on.study$`Smoking status`, on.study$Gender)
```

```{r}
summary(df$Age)
```

```{r}
summary(on.study$Age)
```

